#!/bin/bash

FILE=~/.here

function here() {
    if [ -n $FILE ]; then touch $FILE; fi
    if [ -n "$1" ]
    then
	local key=$1
    else
	local key="here"
    fi
    printf "`sed /$key\ *:/d $FILE`\n$key : `pwd`" > $FILE
}

function go() {
    if [ -n "$1" ]
    then
	local key=$1
    else
	local key="here"
    fi
    local awkprogram='BEGIN { FS=" *: *" } ; /'^$key'\ *:/ {print $2}'
    local target=`awk "$awkprogram" $FILE`
    if [ -n "$target" ]; then
	cd "$target"
    else
	echo "key not found: $key"
    fi
}

function where() {
    if [ ! -f $FILE ]; then return; fi
    if [ -n "$1" ]
    then
	KEY=$1
    else
	KEY=here
    fi
    awk -F\ *:\ * /^$KEY\ *:/\ {print\ \$2} $FILE
}

function del() {
    if [ -n "$1" ]
    then
	KEY=$1
    else
	KEY=here
    fi
    printf "`sed /^$KEY\ *:\ */d $FILE`" > $FILE

}
